version: "3"
services:
  api:
    command: [bash, -c, "npm install --only=production && npm run prisma:generate && node src/index.js"]
    ports:
      - "${API_APP_PORT}:${API_APP_PORT}"
    environment:
      APP_PORT: "${API_APP_PORT}"
      ENABLE_HTTPS: 0
      NODE_ENV: "development"
  client:
    command: [bash, -c, "yarn install && yarn start"]
    ports:
      - "${CLIENT_APP_PORT}:8080"
    environment:
      API_URL: "http://${API_APP_HOST}:${API_APP_PORT}/graphql"
  nginx:
    # Disable the nginx service (https://stackoverflow.com/a/54214179/1743192)
    # since the client will be running on webpack's dev server,
    # which we have set to run on port 8080 inside the webpack config file.
    entrypoint: ["echo", "nginx service disabled"]
    #ports:
      # We don't need nginx to listen for incoming connections
      # since the client will be running on webpack's dev server,
      # which we have set to run on port 8080 inside the webpack config file.
      # So, just expose arbitrary ports that the user is not likely to access
      # This ensures that if we access the production reserved ports 80 or 443 or 3000,
      # during development, say for example, we set these values in the .env file,
      # it does not try to route the requests via nginx,
      # but instead uses the ports to directly the api and client containers via
      # port bindings to the host.
      #- "1234:80"
      #- "1235:443"
      #- "1236:${API_APP_PORT}"
